/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookreview.admin;

import bookreview.Connect;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    Connect conn;
    private BookForm bookForm;
    public AddBook() {
        initComponents();
        conn = new Connect();
        txtTitle.setBackground(new java.awt.Color(0,0,0,1));
        txtCategory.setBackground(new java.awt.Color(0,0,0,1));
        txtfirstname.setBackground(new java.awt.Color(0,0,0,1));
        txtlastname.setBackground(new java.awt.Color(0,0,0,1));
        txtISBN.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        jLabel3 = new javax.swing.JLabel();
        btnConfirm = new rojeru_san.RSButtonRiple();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername.setText("Title");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 341, -1));

        txtTitle.setFont(txtTitle.getFont().deriveFont(txtTitle.getFont().getSize()+2f));
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setBorder(null);
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_________________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 290, 39));

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername1.setText("Category");
        jPanel1.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 341, -1));

        txtCategory.setFont(txtCategory.getFont().deriveFont(txtCategory.getFont().getSize()+2f));
        txtCategory.setForeground(new java.awt.Color(255, 255, 255));
        txtCategory.setBorder(null);
        jPanel1.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 240, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("_________________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 39));

        lblUsername2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername2.setText("ISBN");
        jPanel1.add(lblUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 341, -1));

        txtISBN.setFont(txtISBN.getFont().deriveFont(txtISBN.getFont().getSize()+2f));
        txtISBN.setForeground(new java.awt.Color(255, 255, 255));
        txtISBN.setBorder(null);
        jPanel1.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 240, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_________________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 290, 39));

        txtfirstname.setFont(txtfirstname.getFont().deriveFont(txtfirstname.getFont().getSize()+2f));
        txtfirstname.setForeground(new java.awt.Color(255, 255, 255));
        txtfirstname.setBorder(null);
        jPanel1.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, 39));

        lblUsername3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername3.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername3.setText("Author's Firstname");
        jPanel1.add(lblUsername3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 341, -1));

        lblUsername4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername4.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername4.setText("Author's Lastname");
        jPanel1.add(lblUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 341, -1));

        txtlastname.setFont(txtlastname.getFont().deriveFont(txtlastname.getFont().getSize()+2f));
        txtlastname.setForeground(new java.awt.Color(255, 255, 255));
        txtlastname.setBorder(null);
        jPanel1.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 240, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_________________________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 290, 39));

        rSButtonRiple1.setBackground(new java.awt.Color(51, 51, 51));
        rSButtonRiple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_left_arrow_32px.png"))); // NOI18N
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_book_reading_64px.png"))); // NOI18N
        jLabel3.setText("Add a book");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btnConfirm.setBackground(new java.awt.Color(51, 51, 51));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        boolean success = conn.addBook(txtTitle.getText(), txtISBN.getText(), txtCategory.getText(), txtfirstname.getText(), txtlastname.getText());
        if(success) {
            this.dispose();
            addBookCallback();
            JOptionPane.showMessageDialog(null, "Book successfully added!");
        } else {
            JOptionPane.showMessageDialog(null, "Book already exists in the database!");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel2MouseExited
    
    public void setBookForm(BookForm bookForm) {
        this.bookForm = bookForm;
    }
    
    public void addBookCallback() {
        if (bookForm != null) {
            bookForm.refreshTable();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnConfirm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
